/**
 * Fixture mode (VITE_USE_FIXTURES=1): the UI runs without a backend on recorded SSE streams
 * (frontend/fixtures/sse/*.jsonl) and JSON built from the real tools (frontend/fixtures/api/*.json).
 * Both are generated by scripts/build_frontend_fixtures.py; keys below must match that script.
 */
import type { FixtureLine, SSEEvent, ToolResult } from '../types/contracts'
import type { MixId } from './mixes'

const sseFiles = import.meta.glob('../../fixtures/sse/*.jsonl', { query: '?raw', import: 'default' }) as Record<
  string,
  () => Promise<string>
>
const apiFiles = import.meta.glob('../../fixtures/api/*.json', { import: 'default' }) as Record<
  string,
  () => Promise<unknown>
>

export type ChatFixtureName = 'discover' | 'depot_august' | 'advice_refusal' | 'simulate' | 'roentgen'
export type ApiFixtureName = 'customers' | 'products' | 'portfolios' | 'tools' | 'evals'

export async function loadSSE(name: ChatFixtureName): Promise<FixtureLine[]> {
  const loader = sseFiles[`../../fixtures/sse/${name}.jsonl`]
  if (!loader) throw new Error(`Fixture ${name}.jsonl fehlt`)
  return (await loader())
    .split('\n')
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l) as FixtureLine)
}

const apiCache = new Map<string, Promise<unknown>>()
export function loadApi<T>(name: ApiFixtureName): Promise<T> {
  let p = apiCache.get(name)
  if (!p) {
    const loader = apiFiles[`../../fixtures/api/${name}.json`]
    if (!loader) return Promise.reject(new Error(`Fixture ${name}.json fehlt`))
    p = loader()
    apiCache.set(name, p)
  }
  return p as Promise<T>
}

/** Keys of tools.json, built exactly like the generator script builds them. */
export const toolKey = {
  explain: (customerId: string, start: string, end: string) => `explain|${customerId}|${start}|${end}`,
  lookthrough: (customerId: string) => `lookthrough|${customerId}`,
  simulate: (rate: number, years: number, mix: MixId) => `simulate|${rate}|${years}|${mix}`,
  cost: (productId: string, rate: number, years: number) => `cost|${productId}|${rate}|${years}`,
  suitability: (customerId: string, productId: string) => `suitability|${customerId}|${productId}`,
}

export async function toolFixture<P>(key: string): Promise<ToolResult<P>> {
  const tools = await loadApi<Record<string, ToolResult<P>>>('tools')
  const hit = tools[key]
  if (!hit) throw new Error(`Für diese Eingabe gibt es im Fixture-Modus keine aufgezeichnete Antwort (${key}).`)
  return hit
}

/** Which recorded conversation answers a question. Simple keyword routing, only used in fixture mode. */
export function pickChatFixture(message: string): ChatFixtureName {
  const m = message.toLowerCase()
  if (/(soll ich|kaufen|verkaufen|empfiehl|empfehl|tipp|zuschlagen)/.test(m)) return 'advice_refusal'
  if (/(gefallen|gestiegen|verlust|verloren|august|warum)/.test(m)) return 'depot_august'
  if (/(steckt|steckt drin|enthält|überschneid|röntgen|diversif|klumpen|top.?10|zusammensetz)/.test(m)) return 'roentgen'
  if (/(simul|entwickel|jahre|jahren|hochrechn|prognos|sparplan)/.test(m)) return 'simulate'
  return 'discover'
}

function fixtureSpeed(): number {
  const raw = Number(import.meta.env.VITE_FIXTURE_SPEED ?? 1)
  return Number.isFinite(raw) && raw >= 0 ? raw : 1
}

function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve) => {
    if (signal?.aborted) return resolve()
    const t = setTimeout(resolve, ms)
    signal?.addEventListener('abort', () => (clearTimeout(t), resolve()), { once: true })
  })
}

/** Replays recorded events with their recorded delays (`speed` 0 = instantly, 2 = twice as slow). */
export async function* replay(
  lines: FixtureLine[],
  opts: { speed?: number; signal?: AbortSignal } = {},
): AsyncGenerator<SSEEvent> {
  const speed = opts.speed ?? fixtureSpeed()
  for (const { delay_ms, ...event } of lines) {
    if (opts.signal?.aborted) return
    if (speed > 0 && delay_ms > 0) await sleep(delay_ms * speed, opts.signal)
    if (opts.signal?.aborted) return
    yield event as SSEEvent
  }
}
